### ISSUE TITLE
Bot is not able to respond and getting Error :"WaitBotSays error Error: Queue.pop timeout after 10000"

### ISSUE THREAD

**Issue by Nimish121** [codeforequity-at/botium-bindings#104]
Hello I am running my test with mocha and botium-bindings. Getting below error:

botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at timeoutRequest (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\helpers\Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:4936:13)
  botium-BaseContainer     at ontimeout (timers.js:436:11)
  botium-BaseContainer     at tryOnTimeout (timers.js:300:5)
  botium-BaseContainer     at listOnTimeout (timers.js:263:5)
  botium-BaseContainer     at Timer.processTimers (timers.js:223:10) +0ms
  botium-Convo testCase1.convo.txt: bot says undefined +10s
  botium-Convo Error: testCase1.convo.txt/Line 5: bot says nothing
  botium-Convo     at scriptingEvents.onBotStart.then.then (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:247:33) +2ms
  botium-bindings-main Test Case "testCase1.convo.txt" failed: { TranscriptError: Error: testCase1.convo.txt/Line 5: bot says nothing
  botium-bindings-main     at async.waterfall (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:160:25)
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:473:16
  botium-bindings-main     at next (D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:5329:29)
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:969:16
  botium-bindings-main     at runConversation (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:144:15)
  botium-bindings-main     at async.mapSeries (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:317:9)
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:1140:9
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:473:16
  botium-bindings-main     at iterateeCallback (D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:988:17)
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:969:16
  botium-bindings-main     at D:\backup\sampleBotiumMocha\node_modules\async\dist\async.js:1137:13
  botium-bindings-main     at convoStepDone (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:193:11)
  botium-bindings-main     at scriptingEvents.onBotStart.then.then (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:253:24)
  botium-bindings-main   name: 'TranscriptError',
  botium-bindings-main   transcript:
  botium-bindings-main    Transcript {
  botium-bindings-main      steps: [ [TranscriptStep], [TranscriptStep] ],
  botium-bindings-main      scriptingMemory: {},
  botium-bindings-main      convoBegin: 2019-01-31T09:46:51.863Z,
  botium-bindings-main      convoEnd: 2019-01-31T09:47:06.129Z,
  botium-bindings-main      err:
  botium-bindings-main       Error: testCase1.convo.txt/Line 5: bot says nothing
  botium-bindings-main           at scriptingEvents.onBotStart.then.then (D:\backup\sampleBotiumMocha\node_modules\botium-core\src\scripting\Convo.js:247:33) } } +14s

Attaching my botium.json , package.json and botium.spec.js file.

[Issue.zip](https://github.com/codeforequity-at/botium-bindings/files/2816656/Issue.zip)

**Comment by codeforequity-at** [comment]
Thanks for the good documentation. I will try your sample and give feedback tomorrow.

**Comment by Nimish121** [comment]
Thanks for the comment . It is working fine now
