### ISSUE TITLE
Unable to perform PAUSE operation in directline 3 CONTAINERMODE

### ISSUE THREAD

**Issue by KBANDANA** [codeforequity-at/botium-bindings#128]
Hi Team,

I want to validate 2 bot responses, second response is coming after sometime. How to validate the second response.
I am using the "CONTAINERMODE": "directline3". Where 2nd response is coming max by 1 min. 

I am using the PAUSE statement in below ways, but not working:-

Way :- 1
#bot                                                            
Statement1.
PAUSE 40000 
Statement2.

Way :- 2
#bot                                                            
Statement1.
PAUSE 40000 

#bot                                               
Statement2.

I have used waitforbot logic hook also but it is not working.

#bot                                                   
Statement1.
WAITFORBOT 
Statement2.

Way :- 2
#bot                                                            
Statement1.
PAUSE 40000 

#bot                                               
Statement2.

How to overcome this issue, please suggest.

**Comment by bandanakumari92** [comment]
@codeforequity-at  Please help to update on the issue.

**Comment by codeforequity-at** [comment]
What about this ? Should immediately assert the *Statement1* response, then wait up to 40 seconds for the *Statement2* 

```
#bot
Statement1.

#bot
WAITFORBOT 40000
Statement2.
```

**Comment by codeforequity-at** [comment]
A better place to ask such question is the Botium Forum https://forum.botium.ai/

**Comment by bandanakumari92** [comment]
This is about validating the proactive message of chatbot through botium.  If we are in some workflow and chatbot is expecting some input through user side, and user has responded within 1 min. Then chatbot will send the proactive message. So I need to validate the proactive messages through botium.
Suppose I am in ticket creation flow, ticket creation form is opened. And user not responded within 1 min then it will send the proactive message.

Tried the below steps but got failed.
Please find the below convo

#me
Cancel

#bot
OK. Thank you.

#me
Create a ticket

#bot
OK, Let's create an IT support request.

#bot
Please provide all required details 
CARDS Please provide all required details
FORMS Title|Description|How urgent is your need?
BUTTONS Next|Cancel


#bot
WAITFORBOT 60000
I'm waiting for your response. (This message needs to be validated)

Getting below error:- 
Error: Proactive Messages/Line 22: error waiting for bot - Bot did not respond within 10s
########################################
Proactive Messages/Line 22: error waiting for bot - Bot did not respond within 10s
------------ TRANSCRIPT ----------------------------
#me: Cancel
#bot: OK. Thank you.
#me: Create a ticket
#bot: OK, Let's create an IT support request.
#bot: Please provide all required details
  CARD(Please provide all required details)
  BUTTON(Next | {"action":"Next"})
  BUTTON(Cancel | {"action":"Cancel"})
  FORM(summary | Title)
  FORM(description | Description)
  FORM(priority | How urgent is your need?)
      at BotiumBindings.wrapBotiumError (node_modules\botium-bindings\src\BotiumBindings.js:77:14)       
      at C:\botium\node_modules\botium-bindings\src\BotiumBindings.js:134:33

Please help to resolve this.

**Comment by bandanakumari92** [comment]
Thanks for your response, sure will post in Forum.
